# Day 3. Numpy Exercises

In [1]:
import numpy as np

### a. Create a null vector of size 10 but the fifth value which is 1

In [2]:
a = np.zeros(10)
a [4] = 1
a

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

### b. Create a vector with values ranging from 10 to 49

In [3]:
b = np.arange(10,50)
b

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

### c. Reverse a vector (first element becomes last)

In [4]:
c = np.flip(b)
c

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

### d. Create a 3x3 matrix with values ranging from 0 to 8

In [5]:
d = np.arange(9).reshape(3,3)
d

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

### e. Find indices of non-zero elements from [1,2,0,0,4,0]

In [6]:
e = np.nonzero([1,2,0,0,4,0])
e

(array([0, 1, 4]),)

### f. Create a random vector of size 30 and find the mean value

In [7]:
f = np.random.random(30)
print(np.mean(f))

0.5053031240685234


### g. Create a 2d array with 1 on the border and 0 inside

In [8]:
g = np.ones((10,10))
g[1:-1,1:-1]=0
g

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

### h. Create a 8x8 matrix and fill it with a checkerboard pattern

In [9]:
h = np.zeros((8,8))
h[1::2,::2]=1
h[::2,1::2]=1
h

array([[0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.]])

### i. Create a checkerboard 8x8 matrix using the tile function

In [16]:
i = np.array([[0, 1],[1,0]])
i=np.tile(i,(4,4))
i

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

### j. Given a 1D array, negate all elements which are between 3 and 8, in place

In [23]:
j = np.arange(11)
j[3:9] = np.negative(j[3:9])
j

array([ 0,  1,  2, -3, -4, -5, -6, -7, -8,  9, 10])

### k. Create a random vector of size 10 and sort it

In [27]:
k = np.random.random(10)
k = np.sort(k)
k

array([0.01838739, 0.28129863, 0.45547732, 0.4830001 , 0.60222147,
       0.664783  , 0.68159406, 0.80210689, 0.92948195, 0.93437293])

### l. Consider two random array A anb B, check if they are equal

In [34]:
A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)
equal = A==B
print(equal.all())

False


### m. How to convert an integer (32 bits) array into a float (32 bits) in place?

In [41]:
m = np.arange(10, dtype=np.int32)
print(m.dtype)
m = m.astype(np.float32)
print(m.dtype)

int32
float32


### n. How to get the diagonal of a dot product?

In [44]:
n1 = np.arange(9).reshape(3,3)
n2 = n1 + 1
n3 = np.dot(n1,n2)
print(n3)
print(n3.diagonal())

[[ 18  21  24]
 [ 54  66  78]
 [ 90 111 132]]
[ 18  66 132]
