# Day 5 _ Exercise 1

In [1]:
from scipy import linalg
import numpy as np

### a. Define a matrix A

In [5]:
A = np.array([[2, 2, 3], [4, 5, 6], [7, 8, 9]])
print(A)

[[2 2 3]
 [4 5 6]
 [7 8 9]]


### b. Define a vector b

In [6]:
b = np.arange(1,4)
print(b)

[1 2 3]



### c. Solve the linear system of equations A x = b

In [10]:
x1 = linalg.solve(A,b)

### d. Check that your solution is correct by plugging it into the equation

In [11]:
np.dot(A, x1) == b

array([ True,  True,  True])

### e. Repeat steps a-d using a random 3x3 matrix B (instead of the vector b)

In [12]:
B = np.random.rand(3,3)
x2 = linalg.solve(A,B)
np.dot(A, x2) == B

array([[False, False, False],
       [False, False, False],
       [False, False, False]])

### f. Solve the eigenvalue problem for the matrix A and print the eigenvalues and eigenvectors

In [13]:
eigv,eigv = linalg.eig(A)

### g. Calculate the inverse, determinant of A

In [15]:
invA = linalg.inv(A)
det_invA = linalg.det(A)

### h. Calculate the norm of A with different orders

In [17]:
print("Order " + str(-2) + " matrix A norm:")
print(linalg.norm(A,-2))
print("Order " + str(-1) + " matrix A norm:")
print(linalg.norm(A,-1))
print("Order " + str(1) + " matrix A norm:")
print(linalg.norm(A,1))
print("Order " + str(2) + " matrix A norm:")
print(linalg.norm(A,2))

Order -2 matrix A norm:
0.3238716064329893
Order -1 matrix A norm:
13.0
Order 1 matrix A norm:
18.0
Order 2 matrix A norm:
16.958678200465908
